### ISSUE TITLE
Full download

### ISSUE THREAD

**Issue by Superhzf** [john-hewitt/control-tasks#5]
Hi Sir,

Thanks for your wonderful work! Per the information in the `download_example.sh`, it only downloads a small sample of the whole dataset, and it says that we should uncomment the full download line if we want, but I don't see the commented full download line.

Do I miss anything here?

Zach

**Comment by john-hewitt** [comment]
Hi Zach,

Whoops, sorry about that! I won't put up downloads for the hdf5 files for the whole EWT dataset, but the EWT corpus conll files are available at their canonical location here: https://github.com/UniversalDependencies/UD_English-EWT

The scripts in the `scripts/` folder should help you make the raw and hdf5 files from those conll files.

**Comment by Superhzf** [comment]
Hi Sir,

Thanks for your quick reply, I will take look.

Zach
